use std::path::{Path, PathBuf};

use anyhow::Context;
use rusqlite::{params, Connection};

use crate::{db, root_snapshot, util};

#[derive(Debug, Clone)]
pub struct ExportResult {
    pub path: Option<PathBuf>,
    pub file_count: usize,
    pub text: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    pub relative_path: String,
    pub crc32: String,
}

pub fn export_root(
    conn: &Connection,
    root: &db::RootRow,
    output: Option<&Path>,
) -> anyhow::Result<ExportResult> {
    let entries = db::sfv_entries_for_root(conn, &root.id)?;
    if entries.is_empty() {
        anyhow::bail!(
            "root {} has no stored CRC32 metadata to export as SFV",
            root.path
        );
    }
    let file_count = entries.len();
    let text = render_root_manifest(root, entries);
    if let Some(output) = output {
        write_manifest(output, &text)?;
        Ok(ExportResult {
            path: Some(output.to_path_buf()),
            file_count,
            text: None,
        })
    } else {
        Ok(ExportResult {
            path: None,
            file_count,
            text: Some(text),
        })
    }
}

pub fn export_root_default_path(
    conn: &Connection,
    root: &db::RootRow,
) -> anyhow::Result<ExportResult> {
    let path = PathBuf::from(format!(
        "{}.sfv",
        root_snapshot::safe_file_stem(&root_snapshot::short_root_name(root))
    ));
    export_root(conn, root, Some(&path))
}

pub fn export_directory_default_path(
    conn: &Connection,
    root: &db::RootRow,
    relative_dir: &str,
) -> anyhow::Result<ExportResult> {
    let relative_dir = normalize_relative_dir(relative_dir);
    let dir_path = if relative_dir == "." {
        PathBuf::from(&root.path)
    } else {
        PathBuf::from(&root.path).join(&relative_dir)
    };
    if !dir_path.is_dir() {
        anyhow::bail!(
            "SFV export target is not a local directory: {}",
            dir_path.display()
        );
    }
    let dir_name = if relative_dir == "." {
        root_snapshot::short_root_name(root)
    } else {
        Path::new(&relative_dir)
            .file_name()
            .map(|name| name.to_string_lossy().to_string())
            .unwrap_or_else(|| root_snapshot::short_root_name(root))
    };
    let path = dir_path.join(format!("{}.sfv", root_snapshot::safe_file_stem(&dir_name)));
    export_directory(conn, root, &relative_dir, &path)
}

pub fn export_directory(
    conn: &Connection,
    root: &db::RootRow,
    relative_dir: &str,
    output: &Path,
) -> anyhow::Result<ExportResult> {
    let entries = sfv_entries_for_directory(conn, &root.id, relative_dir)?;
    if entries.is_empty() {
        anyhow::bail!(
            "directory {} has no stored CRC32 metadata to export as SFV",
            relative_dir
        );
    }
    let file_count = entries.len();
    let text = render_manifest(
        &format!("{}:{}", root.path, normalize_relative_dir(relative_dir)),
        entries,
    );
    write_manifest(output, &text)?;
    record_exported_manifest(conn, root, output)?;
    Ok(ExportResult {
        path: Some(output.to_path_buf()),
        file_count,
        text: None,
    })
}

fn render_root_manifest(root: &db::RootRow, entries: Vec<db::SfvExportEntry>) -> String {
    render_manifest(&root.path, entries)
}

fn render_manifest(source: &str, entries: Vec<db::SfvExportEntry>) -> String {
    let mut text = String::new();
    text.push_str(&format!(
        "; Generated by gremlin from metadata for {}\n",
        source
    ));
    for entry in entries {
        text.push_str(&format!("{} {}\n", entry.relative_path, entry.crc32));
    }
    text
}

fn write_manifest(path: &Path, text: &str) -> anyhow::Result<()> {
    std::fs::write(path, text).with_context(|| format!("writing SFV {}", path.display()))
}

fn record_exported_manifest(
    conn: &Connection,
    root: &db::RootRow,
    path: &Path,
) -> anyhow::Result<()> {
    let root_path = Path::new(&root.path);
    let relative_path = util::relative_path(root_path, path)?;
    let basename = util::basename(path)?;
    let parent_path = util::parent_path(&relative_path);
    let metadata = path
        .metadata()
        .with_context(|| format!("reading metadata for {}", path.display()))?;
    let modified_at = metadata.modified().ok().map(util::system_time_rfc3339);
    db::insert_path_observation(
        conn,
        db::PathObservationInput {
            machine_id: &root.machine_id,
            root_id: &root.id,
            relative_path: &relative_path,
            basename: &basename,
            parent_path: &parent_path,
            size_bytes: metadata.len(),
            modified_at: modified_at.as_deref(),
            content_id: None,
        },
    )?;
    conn.execute(
        "UPDATE path_observations SET content_id = NULL WHERE root_id = ?1 AND relative_path = ?2",
        params![root.id, relative_path],
    )?;
    Ok(())
}

pub fn parse_line(line: &str) -> Option<Entry> {
    let trimmed = line.trim();
    if trimmed.is_empty() || is_comment(trimmed) {
        return None;
    }
    let (path, crc) = trimmed.rsplit_once(char::is_whitespace)?;
    let crc = crc.trim();
    if crc.len() != 8 || !crc.chars().all(|ch| ch.is_ascii_hexdigit()) {
        return None;
    }
    let relative_path = path.trim().trim_start_matches('*').to_string();
    if relative_path.is_empty() {
        return None;
    }
    Some(Entry {
        relative_path,
        crc32: crc.to_ascii_uppercase(),
    })
}

pub fn is_comment(line: &str) -> bool {
    let trimmed = line.trim_start();
    trimmed.starts_with(';') || trimmed.starts_with('#')
}

fn sfv_entries_for_directory(
    conn: &Connection,
    root_id: &str,
    relative_dir: &str,
) -> rusqlite::Result<Vec<db::SfvExportEntry>> {
    let relative_dir = normalize_relative_dir(relative_dir);
    if relative_dir == "." {
        return db::sfv_entries_for_root(conn, root_id);
    }
    let prefix = format!("{relative_dir}/");
    let like = format!("{}%", escape_like_pattern(&prefix));
    let start = prefix.chars().count() + 1;
    let mut stmt = conn.prepare(
        r#"
        SELECT substr(p.relative_path, ?3), c.crc32
        FROM path_observations p
        JOIN content_objects c ON c.id = p.content_id
        WHERE p.root_id = ?1
          AND p.status = 'present'
          AND p.relative_path LIKE ?2 ESCAPE '\'
          AND c.crc32 IS NOT NULL
        ORDER BY p.relative_path ASC
        "#,
    )?;
    let rows = stmt.query_map(params![root_id, like, start as i64], |row| {
        Ok(db::SfvExportEntry {
            relative_path: row.get(0)?,
            crc32: row.get(1)?,
        })
    })?;
    rows.collect()
}

fn normalize_relative_dir(relative_dir: &str) -> String {
    let trimmed = relative_dir.trim_matches('/');
    if trimmed.is_empty() || trimmed == "." {
        ".".to_string()
    } else {
        trimmed.to_string()
    }
}

fn escape_like_pattern(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('%', "\\%")
        .replace('_', "\\_")
}
