use std::path::{Path, PathBuf};

use anyhow::Context;
use rusqlite::Connection;

use crate::{db, root_snapshot};

#[derive(Debug, Clone)]
pub struct ExportResult {
    pub path: Option<PathBuf>,
    pub file_count: usize,
    pub text: Option<String>,
}

pub fn export_root(
    conn: &Connection,
    root: &db::RootRow,
    output: Option<&Path>,
) -> anyhow::Result<ExportResult> {
    let entries = db::sfv_entries_for_root(conn, &root.id)?;
    if entries.is_empty() {
        anyhow::bail!(
            "root {} has no stored CRC32 metadata to export as SFV",
            root.path
        );
    }
    let file_count = entries.len();
    let text = render_root_manifest(root, entries);
    if let Some(output) = output {
        write_manifest(output, &text)?;
        Ok(ExportResult {
            path: Some(output.to_path_buf()),
            file_count,
            text: None,
        })
    } else {
        Ok(ExportResult {
            path: None,
            file_count,
            text: Some(text),
        })
    }
}

pub fn export_root_default_path(
    conn: &Connection,
    root: &db::RootRow,
) -> anyhow::Result<ExportResult> {
    let path = PathBuf::from(format!(
        "{}.sfv",
        root_snapshot::safe_file_stem(&root_snapshot::short_root_name(root))
    ));
    export_root(conn, root, Some(&path))
}

fn render_root_manifest(root: &db::RootRow, entries: Vec<db::SfvExportEntry>) -> String {
    let mut text = String::new();
    text.push_str(&format!(
        "; Generated by gremlin from metadata for {}\n",
        root.path
    ));
    for entry in entries {
        text.push_str(&format!("{} {}\n", entry.relative_path, entry.crc32));
    }
    text
}

fn write_manifest(path: &Path, text: &str) -> anyhow::Result<()> {
    std::fs::write(path, text).with_context(|| format!("writing SFV {}", path.display()))
}
